on:
  push:
    branches:
      - master

jobs:
  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Release
        run: |
          npm i semantic-release @semantic-release/exec @semantic-release/release-notes-generator -g
          npm i
          npm run release-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
